F03
GeoffreyRavenet/crazee-burger pull request #3
Opened 2023-01-16 23:56 UTC by GeoffreyRavenet

2023-01-17 12:47 UTC, Mart95Dev commented on src/components/pages/login/LoginForm.jsx
> +        <button>Accéder à mon espace<IoIosArrowForward/></button>
Pour la suite du projet, on va réaliser des components reutilisables. cet élément button est un component reutilisable. Essaie de le transformer en component.

2023-01-17 12:48 UTC, Mart95Dev commented on src/components/pages/login/LoginPage.jsx
> +      <div className="logo">
idem pour cet élément.

2023-01-19 09:06 UTC, vileaddev requested changes
Un dernier changement à faire et ce devrait être bon ✅

2023-01-19 09:06 UTC, vileaddev commented on src/components/reusable-ui/Logo.jsx
> +            <Link to={`/`}>
Pourquoi le logo est clickable ? Il ne devrait pas l'être

2023-01-19 09:06 UTC, vileaddev commented on src/components/reusable-ui/Logo.jsx
> +  a{
du coup ce "a" n'a rien à faire ici -> à retirer

2023-01-19 09:38 UTC, vileaddev approved these changes

2023-01-19 09:46 UTC, merged